name: madebyryan
favicon: null
layout_spectrum: 0.024322235258296132
typography_spectrum: 0.3390866373665631
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.030437849927693605
  lightness: 0.06931622861884534
  saturation: 0.42643359838984907
  rhythmicContrast: 0.030705703888088465
purpose: []
